import Nav from "./components/Nav";
import "./globals.css";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import Hydrate from "./components/Hydrate";
import { Roboto, Lobster_Two } from "next/font/google";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto"
});

const lobster = Lobster_Two({
  weight: "700",
  subsets: ["latin"],
  variable: "--font-lobster"
});

export const metadata = {
  title: "Next 13 Ecommerce",
  description: "Generated by create next app"
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  // fetch the user
  // const session = await getServerSession(authOptions);
  // console.log(session); // shows the user object which contains the name, email & iamge properties

  return (
    <html className={`${roboto.variable} ${lobster.variable}  `} lang="en">
      <Hydrate>
        <Nav />
        {children}
      </Hydrate>
    </html>
  );
}
